### PR TITLE
feat(endpoint): built first endpoint for POST /movies

### PR DESCRIPTION
**Pull request by nathankhuu**
What: Defined the POST /movies route
Why: To handle requests for defined routes
Details:
Seeded database with movies
Created movie model and test
Built first endpoint for /movies

### CODE REVIEW

**Comment by vinay-pad** [comment]
@nathankhuu i think you need to setup an integration with travisCI in order to run your tests.

**Comment by vinay-pad** [comment]
you can follow the instructions [here](https://www.notion.so/lob/Code-Review-a2d39ae6bfc043ca9a396a78a25ca39f#7638aa735e7f4302895e58cfd692d5a1)

**Comment by jesscxu** [comment]
@nathankhuu i think you also want to add `.DS_Store` to the `.gitignore` file

**Review by jesscxu — APPROVED** [review]
LGTM pending comments!

**Review by vinay-pad — APPROVED** [review]
LGTM!

**Pull request merged**
