### PR TITLE
refactor(movies): save name to database

### PR DESCRIPTION
**Pull request by nathankhuu**
What: update application code to save name
Why: to populate name column with new movie titles

### CODE REVIEW

**Review by nyergler — APPROVED** [review]

**Review by nyergler — COMMENTED** [review]
Just re-reading; do you need a migration with this step, as well?

**Comment by nathankhuu** [comment]
I think this step is to update the code to save name, so both name and title get populated. Do I need a migration to do this? I know the next step is a migration to backfill the null values of name

**Comment by nyergler** [comment]
Ah, you're right; I didn't notice that the migration was in #4.

Carry on :)

**Comment by vinay-pad** [comment]
@nathankhuu this isn't really saving `name` is it? its just adding `name` in the response during serialization. maybe update the description?

**Review by vinay-pad — APPROVED** [review]
LGTM!

**Pull request merged**
